import '../App.css';
import React from 'react'


const About = () =>{
  return(
    <div>
    <h1>About Page</h1>

    <p>THIS IS A POKEMON FINDER APPLICATION CURRENTLY IN BETA</p>

    <p>1. TO USE CLICK HOME</p>

    <p>2. THEN RIGHT CLICK THE SCREEN AND CHOOSE INSPECT</p>

    <p>3. A MENU WILL POP UP DONT WORRY ABOUT THE THINGS YOU SEE THERE RIGHT NOW</p>

    <p>4. FIND AT THE TOP OF THIS NEW MENU A TAB TITLED CONSOLE</p>

    <p>5. CLICK THE TAB TITLED CONSOLE</p>

    <p>6. IN THIS CONSOLE AREA IS WHERE THE INFORMATION WILL SHOW UP AT THIS CURRENT TIME</p>

    <p>7. NOW BACK TO THE INPUT AREA TYPE THE NAME OF THE POKEMON YOU WANT TO FIND FOR YOUR
    CURRENT GAME</p>

    <p>8. PRESS SUBMIT AND A LIST WILL GENERATE SHOWING THE NAME OF THE GAME AND THE ROUTE(S)
    THIS POKEMON CAN BE FOUND AT</p>

    <p>**NOTE**</p>

  <p>IF NO POKEMON LIST SHOWS UP THEN PLEASE RE-CHECK THE SPELLING OF THE POKEMON THAT YOU
    ARE LOOKING FOR.</p>

  <p>POPULATED ALL POKEMON UP TO GEN 8</p>

    </div>
  )
}

export default About
